### ISSUE TITLE
Brush up pages of /area, /items / エリア・アイテムページのLP化・ブラッシュアップ

### ISSUE THREAD

**Issue by eleewinroader** [eleewinroader/mp-ecokaishu#34]
http://www.eco-kaishu.jp/items/XXXXXX
1. Brush up following documents #34_Requirement definition

**Comment by phuongty** [comment]
I've completed 30% progress. Source code are committed to git.

**Comment by eleewinroader** [comment]
I looked through  your source. Details will be discussed later.
I'm afraid to say that you have to work on single-items.php or single-area.php, not archive-XX.php.
Sorry for late to mention it.

**Comment by phuongty** [comment]
I've completed 70% progress. Source code are committed to git.

**Comment by phuongty** [comment]
Completed. Please check on git. Thanks :)

**Comment by eleewinroader** [comment]
# Feedback 1

## Suggestions 

- [ ] 1. Make clear the structure in terms of Semantics.
- [ ] 2. Take `.container` off
- [ ] 3. Adjust the background
- [ ] 4. Update the text
- [ ] 5. Apply grid system
- [ ] 6. Remove
- [ ] 7. Update images and text


------------------------------
------------------------------



## 1. Make clear the structure in terms of Semantics.

It's a very very very important part to markup html.

For example, line 33, use `<div>` instead of `<section>` .
Because you use `<section>` to wrap the part of intro,
it makes `<h2>`  represent only the intro part.
`<h2>`  is a heading representing the whole `<article>`.

If I were you, I will markup like the (1) part of the bottom image.
It's a suggestion. You don't have to follow it.

Regardless of the markup, the sturcture should be like below.
Drag and paste your source on https://gsnedders.html5.org/outliner/ .
And compare yours with the below one and make same it.

```
1. 家具の処分・廃棄を考えているならエコ回収
    1. Untitled Section
    2. 練馬区で不用品回収をお考えの方へエコランドにお任せください
        1.  エコランドが選ばれる理由
            1. 明確な料金体系 
            2. 事前見積&スピード対応
            3. 安心の実績
        2. 明確な料金体系
            1. 基本料金
            2. 品物ごとの料金
                1. 各家電・パソコンのサイズ別料金
                    1. テレビ
                    2. 冷蔵庫
                    3. エアコン
                    4. テレビ
                    5. 衣類乾燥機
                    6. エアコン
                2. 各品物のランク別料金
                    1. Aランク 540円
                    2. Bランク 1,080円
                    3. Cランク　1,620円
                    4. Dランク　2,160円
                    5. Eランク　2,700円
                    6. Fランク　3,240円
                    7. Gランク　4,320円
                    8. Hランク　5,940円
                    9. Iランク　7,560円
                    10. Jランク　9,720円
                    11. Kランク　12,960円
            3. 特殊作業料金
                1. 外階段作業
                2. 内階段作業
                3. 解体作業
                4. 吊り下ろし作業
                5. 養生作業
                6. エアコン取り外し工事
            4.  オプション料金
                1. 時間帯指定サービス
                2. 当日集荷サービス
                3. 夜間指定サービス
                4. レディースサービス
                5. 目の前あんしんデータ消去サービス
        3. 買取について
            1. 家電
            2. 家電
            3. 楽器
            4. パソコン
        4. 事前見積&スピード対応
            1. ネット/電話で事前見積
            2. プロに運び出しもお任せ
            3. 私たちがまいります
            4. 私たちがうかがいます
        5. 安心の実績
            1. 大手企業との提携が信頼の証
            2. 有名メディアにも多数掲載
        6. ご利用の流れ
            1. 見積もり依頼
            2. 集荷
            3. お支払い
            4. エコオク
            5. お申し込みの前に確認ください‼︎
        7. お客様の声
        8. よくある質問
    3. ただ今のキャンペーン
    4. Untitled Section
    5. エコ回収 全コンテンツ
        1. サービス概要
        2. サービス申込
        3. エリア別口コミ･評判
        4. アイテム別口コミ･評判
        5. 当サイトについて
```


## 2. Take `.container` off

line 257
According to Basic regulations in 1.The grid system,
`.container` cannot include another `.container`.

## 3. Adjust background

* When PC, make the background full

The truck background is intended the full background like http://www.invisionapp.com/.
Can you make the image full? If it's difficult to make it full,
blur the edge of image naturally and place the image center, no-repeat.

* When Mobile, remove the background

## 4. Update the text.

As I mentioned, the text is up to date.
You can find it #45_Materials in Wiki.

This part is same as #45.
After finish #45, bring the source and paste it.

## 5. Apply grid system

Don't use `<table>` for layout. 
Refer to http://www.eco-kaishu.jp/problems/
(Actually Takuyasan marked up the page. You can ask him to help.)

## 6. Remove

The contents of this part is not prepared.
It postpones to release in 2.5 and later.

## 7. Update images and text

Now you can get the images and text.
Sorry for late.

Refer to the Medai reports http://www.eco-land.jp/welcome/

### Image

Images: Creative Cloud Files ▸ 01_素材 ▸ 03_ロゴ(他社) ▸ 04_メディア

### Text

150126_1.jpg
理念と経営
2014年01月10日
2014年1月10日、「理念と経営2月号」の特集にエコランドを運営する株式会社ウインローダーについて掲載して頂きました！

150126_2.jpg
日経ウーマン
2013年08月05日
2013年8月5日発行の日経ウーマン別冊に、エコランドの整理収納アドバイザー星が登場致しました！

150126_3.jpg
サンキュ！
2013年05月01日
2013年5月1日発売の「サンキュ！6月号」に、エコランドのお片づけサービスが掲載されました！

150126_4.jpg
ガイアの夜明け
2011年12月20日
2011年12月20日、エコランドのお片づけサービスについてガイアの夜明けで紹介して頂きました！

150126_5.jpg
トコトンハテナ
2010年1月24日
2010年1月24日放送の、テレビ東京【トコトンハテナ】もりちえみさんが年末のエコ回収に密着取材！

150126_6.jpg
東京カワイイ☆ＴＶ
2010年1月23日
1月23日・30日放送のNHK【東京カワイイ☆TV】に俳優の沢村一樹さん・歌手のBENIさんがエコランドに!

![untitled](https://cloud.githubusercontent.com/assets/6733350/5897017/2b59c8ae-a582-11e4-8dd7-f042fba8a6c4.png)

**Comment by phuongty** [comment]
I fixed the feedback. Please check again.
