### ISSUE TITLE
Create the available services page / エコ回収できるモノ・できないモノ

### ISSUE THREAD

**Issue by eleewinroader** [eleewinroader/mp-ecokaishu#40]
http://www.eco-kaishu.jp/unavailable
1. Create and display the page following document #40_requirement definition
2. Modify the text and like in the header/footer menu

**Comment by phuongty** [comment]
Completed 100%

**Comment by eleewinroader** [comment]
# Feedback 1

## Suggestions

- [ ] 1. Create custom post type, unavailable
- [ ] 2. Create archive-unavailable.php
- [ ] 3. Apply the `.headerPage` format.
- [ ] 4. Remove `.unavailable` in line 28 of "page-unavailable.php"
- [ ] 5. Apply the `.summary` format.
- [ ] 6. Adjust styling of `.al_c`
- [ ] 7. Remove padding and border
- [ ] 8. Apply `.listDefi` and markup it using `<dl><dt><dd>`
- [ ] 9. Apply `.listDefi` and markup it using `<ul><li>`

---
---

## 1. Create custom post type

* Name : unavailable
* Label : エコ回収利用できる / できないアイテム
* Singular label : アイテム
* Has archive : True
* Supports : Title, Editor, CustomerFields

## 2. Create archive-unavailable.php

I commited the "archive-unavailable.php", pull it.

After you create the custom post type, unavailable,
and make a dummy post in the custom post type,
Then you may can access to /unavailable and find the "unavailable" page show.

## 3. Apply the `.headerPage` format

Refer to line 8-28 in "archive-unavailable.php" that I created.
The point is
`<header>` has to include heading elements to represent a title of `<article>`
and `<nav>` represents a navigation of the page.

## 4. Remove `.unavailable`

In line 28 of "page-unavailable.php", you don't have to specify elements for CSS.
because it is operated as an archive page of custom post type.
Refer to the php function `getArticleClass()` in functions.php

## 5. Apply the `.summary` format.

Refer to line 33-38 in "archive-unavailable.php".

To appeal what the page is about,
in the top, the thesis statement is applied `.summary` styling.

The setting is line 110 in `_scss/pages/_article.scss`.

## 6. Adjust styling of `.al_c`

* Markup as `<ul><li>` named `.listSummary`.
* Set `$maxWidth` as the width, when bigger screens.

## 7. Remove padding and border

Don't add paddings and borders on the `.col`
because it is likely to make the grid system mess and unaccurate.

## 8. Apply `.listDefi`

Markup as `<dl><dt><dd>` named `.listDefi`
(Refer to `.listDefi` in `/_scss/parts/_list.scss`)

Update to the latest text
The latest text is always on the github.
Don't bring the materials from Illustarator that is displayed only the layout.
All of the materials are pointed in wiki on the github.

## 9. Apply `.listDefi`

Markup as `<ul><li>` named `.listDefi`


![150201_40_feedback](https://cloud.githubusercontent.com/assets/6733350/5991501/1c923a32-aa36-11e4-87e1-c0974ba94e73.png)

**Comment by nagahiroasami** [comment]
OK
