### ISSUE TITLE
Brush up the price page / 料金案内ページのブラッシュアップ

### ISSUE THREAD

**Issue by eleewinroader** [eleewinroader/mp-ecokaishu#45]
http://www.eco-kaishu.jp/price
1. Brush up following documents #34_Requirement definition

**Comment by eleewinroader** [comment]
# Suggestions

- [ ] 1. Update the text
- [ ] 2. Remove the background colour 
- [ ] 3. Modify the Tab part
- [ ] 4. Styling for an appendix
- [ ] 5. Styling `.item` for small screen
- [ ] 6. Rename `<section>` id
- [ ] 7. Modify `<table>`

------------------------------
------------------------------

# 1.update the new text

Sorry for late.
I created the latest document, #45_Materials.


# 2. remove background

Take the pink background off.


# 3. Modify the Tab part

First of all, you should understand HTML5 semantics.

**Don't use a html element for styling**

> Elements, attributes, and attribute values in HTML are defined (by this specification) to have certain meanings (semantics)
> http://www.w3.org/TR/html5/dom.html#semantics-0

**Structure of a page**

Pay attention to the structure of page represented by html5.
Refer to http://www.w3.org/TR/html5/sections.html#the-article-element

Check the structure from a below link when you finish to code.
https://gsnedders.html5.org/outliner/

Simply, you can remember
sectioning content should include one heading element, `<h1> <h2> <h3>` ... 

> Sectioning content is content that defines the scope of headings and footers.
> http://www.w3.org/TR/html5/dom.html#sectioning-content-0

**Here is my suggestion**

* replace `<section>` with `<div>`
* remove `<ul></li>`
	* put `<h3>` on the title
	* put `<div>` on the other texts
* hide other texts(div.tab) when small screen

**Example** 

```
<div class="linkMenu">
	<h3><a href="#basicCharges" class="active">基本料金</a></h3>
	<div class="tab"><a href="#itemCharges">品物ごとの料金</a></div>
	<div class="tab"><a href="#spworksCharges">特殊作業料金</a></div>
	<div class="tab"><a href="#optionsCharges">オプション料金</a></div>
</div>
```

# 4. Styling of an appendix

Put appendix class and `<small>` when (※) is.

> The small element represents side comments such as small print.
> http://www.w3.org/TR/html5/text-level-semantics.html#the-small-element

Example

`<p class="appendix"><small>※金庫やエレクトーンなど重量のあるモノは重量によって料金ランクが決まります。</small></p>`


# 5. Styling `.item` for the small screen

Remove the border and padding when the screen is small.


# 6. Rename `<section>` id

* 6-1 `#basicCharges`
* 6-2 `#itemCharges`
* 6-3 `#spworksCharges`
* 6-4 `#optionsCharges`


# 7. Modify `<table>` 

**Remove direct style settings on html**

You don't need to set as you did on line 89 of _price.scss
because, I assume, the compass library already has those settings.

`<table cellpadding="0" cellspacing="0" width="100%" border="0">`
↓
`<table>`

I recommend to set styles in the style sheet,
not directly whatever styles on a html tag.

**Make full use of `<table>`**

Look through the table element of html5.
http://www.w3.org/TR/html5/tabular-data.html#the-table-element

It's better to make full use of table elements like
`<thead> <tbody> <tfoot>`

**Comment by phuongty** [comment]
I fixed the feedback. Please check again.
