### ISSUE TITLE
Bugs in 5/10 of the inquiry form 

### ISSUE THREAD

**Issue by eleewinroader** [eleewinroader/mp-ecokaishu#47]
http://www.eco-kaishu.jp/inquiry/

1. Reports from customers who cannot carry out any actions from 5/10 of the form

Customer 1
* OS: Windows 8 (PC)
* Browser : Internet Explorer

Customer 2
* Device : iPad

**Comment by phuongty** [comment]
Fixed.

**Comment by nagahiroasami** [comment]
The same problem occured on the staging environment.
•OS: Windows 7 (PC)
•Browser : Google Chrome
