### ISSUE TITLE
Add staffs and profile images

### ISSUE THREAD

**Issue by eleewinroader** [eleewinroader/mp-ecokaishu#53]
http://www.eco-kaishu.jp/staff

1. Add the name and profile image of Oki-san on the staff page
2. Add the new staff Hori-san, Hashimoto-san

**Comment by eleewinroader** [comment]
**Further tasks**
Update the latest list of staff and profile image
Build a system to update and check the staff list at least monthly

**Comment by nagahiroasami** [comment]
I couldn't find a profile image of Oki-san

**Comment by eleewinroader** [comment]
Please check again. I uploaded the images.
